### PR TITLE
Fixes for THR 1.40.0a firmware

### PR DESCRIPTION
**Pull request by sosedoff**
Preamble has changes and also there's an extra message being passed on start.

### CODE REVIEW

**Comment by sosedoff** [comment]
This worked for me on OSX, however it seems like it might not work on Linux (im using raspberry pi for this).

**Comment by sosedoff** [comment]
Eh, i spoke too soon - seems like this was not working on OSX either

**Comment by warmans** [comment]
Awesome, thanks.

**Comment by warmans** [comment]
Oops I should probably read all the comments before merging stuff. 😅

**Pull request merged**
